accounts/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    # path('myAccount/',views.myAccount, name='account_url'),
    path('registerUser/', views.registerUser, name = 'registerUser'),
    path('registerRestaurant/', views.registerRestaurant, name = 'registerRestaurant'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('myAccount/', views.myAccount, name = 'myAccount'),
    path('custDashboard/', views.custDashboard, name = 'custDashboard'),
    path('restaurantDashboard/', views.restaurantDashboard, name = 'restaurantDashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name="activate"),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('restaurant/', include('restaurant.urls')),
    path('customer/', include('customers.urls')),
    path('newsletter-signup/', views.newsletter_signup, name='newsletter_signup'),


]

orders/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap




urlpatterns = [
    path('place-order/', views.place_order, name = 'place_order'),
    path('create_order_api/', views.create_order_api, name='create_order_api'),
    path('payment-webhook/', views.payment_webhook, name='payment_webhook'),
    path('order_complete/', views.order_complete, name='order_complete'),
    # path('restaurant_cash_order/', views.restaurant_cash_order, name='restaurant_cash_order'),

    
]

orderzy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomeSitemap
from marketplace.sitemaps import MarketplaceSitemap, RestaurantSitemap
from customers.sitemaps import CustomerSitemap
from accounts.sitemaps import AccountsSitemap
from orders.sitemaps import OrdersSitemap
from django.views.generic import TemplateView

sitemaps = {
    'home': HomeSitemap,
    'marketplace': MarketplaceSitemap,
    'restaurant': RestaurantSitemap,
    'customers': CustomerSitemap,
    'accounts': AccountsSitemap,
    'orders': OrdersSitemap,
}
urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("admin/", admin.site.urls),
    path('', views.home, name = 'home'),
    path('base/', views.base, name = 'base'),
    
    path('', include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),
    #CART
    path('cart/', MarketplaceViews.cart, name='cart'),
    
    #SEARCH PATH
    path('search/', MarketplaceViews.search, name='search'),
    
    path('checkout/', MarketplaceViews.checkout, name='checkout'),
    
    
    path('orders/', include('orders.urls')),
    
    path('about/', views.about_us, name='about_us'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact_us, name='contact_us'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('refund_policy/', views.refund_policy, name='refund_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),

    
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.fields.related import  OneToOneField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point



class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email=None,phone_number=None, password=None,**extra_fields):
        if not username:
            raise ValueError('Username is required')
        if not password:
            raise ValueError('Password is required')
        
        if '@' in username:
            email = self.normalize_email(username)
            phone_number = None
        else:
            email = None
            phone_number = username
        
        user = self.model(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            phone_number=phone_number,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    
    
    def create_superuser(self, first_name, last_name, username, email=None,phone_number=None, password=None, **extra_fields):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            password=password,
            **extra_fields
        )
        user.is_admin=True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    
    RESTAURANT = 1
    CUSTOMER = 2
 
    
    ROLE_CHOICE = (
        (RESTAURANT, 'Restaurant'),
        (CUSTOMER, 'Customer')

        
    )
    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True, blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)
    
    #required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False) 

 
    USERNAME_FIELD = 'username' 
    REQUIRED_FIELDS = ['first_name', 'last_name']
    
    objects = UserManager()

    def __str__(self):
        return self.username
    
    def save(self, *args, **kwargs):
        if '@' in self.username:
            self.email = self.username
            self.phone_number = None
        else:
            self.email = None
            self.phone_number = self.username

        super(User, self).save(*args, **kwargs)
    
    def has_perm(self,perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Restaurant'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}".strip()
    


class UserProfile(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE, blank=True, null = True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null = True)
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null = True)
    address = models.CharField(max_length=250, blank=True, null = True)
    country = models.CharField(max_length=15, blank=True, null = True)
    state = models.CharField(max_length=15, blank=True, null = True)
    city = models.CharField(max_length=15, blank=True, null = True)
    pin_code = models.CharField(max_length=6, blank=True, null = True)
    latitude = models.CharField(max_length=20, blank=True, null = True)
    longitude = models.CharField(max_length=20, blank=True, null = True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    

    
    def __str__(self):
        if self.user:
            return self.user.username or 'No username'
        return 'No user'
    
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
            return super(UserProfile, self).save(*args, **kwargs)
        return super(UserProfile, self).save(*args, **kwargs)
    
    # models.py


class ContactMessage(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=100)
    message = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} at {self.sent_at}"



class Newsletter(models.Model):
    email = models.EmailField(unique=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from .models import *
from .validators import allow_only_images_validator

        
class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter your password'
        })
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username','password']
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Please enter your email...'
        })
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')

        if not username:
            raise forms.ValidationError("Username is required.")
        
        if '@' in username:
            email = username
            if User.objects.filter(username=email).exists():
                raise forms.ValidationError("User with this Email already exists.")
        else:
            phone_number = username
            if User.objects.filter(username=phone_number).exists():
                raise forms.ValidationError("User with this Phone Number already exists.")

        return cleaned_data
    
class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder' : 'Start Typing...', 'required':'required'}))
    profile_picture = forms.FileField(widget = forms.FileInput(attrs={'class':'btn btn-info'}), validators=[allow_only_images_validator])
    cover_photo = forms.FileField(widget = forms.FileInput(attrs={'class':'btn btn-info'}), validators=[allow_only_images_validator])
    
    
    class Meta:
        model = UserProfile
        fields = ['profile_picture','cover_photo','address','country','state','city','pin_code','latitude','longitude']
        
        
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field =='latitude' or field == 'longitude':
                self.fields[field].widget.attrs['readonly'] = 'readonly'
                
                

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','phone_number']
        
        



class LoginForm(forms.Form):
    identifier = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Email or Mobile Number'}))
    password = forms.CharField(widget=forms.PasswordInput())



class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'message']

templates/accounts/custDashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Dashboard  {% endblock %} 

{% block content %}

{% block extra_css %}
<style>
    a {
        text-decoration: none;
    }
    
</style>
{% endblock extra_css %}
{% include 'includes/alerts.html' %}

<div class="main-section">
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    {% include 'includes/c_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Overview</h5>
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="card-header">Total Orders</div>
                                        <div class="card-body text-center">
                                            <a href="">
                                                <h5 class="card-title">{{orders_count}}</h5>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="card-header">Logged in as: <b>{{user.email}}</b></div>
                                        <div class="card-body text-center">
                                            <a href="{% url 'cprofile' %}">
                                                <h5 class="card-title"> <i class="fa fa-edit"></i>Edit Profile</h5>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                                
                                <br><br>
                            </div>
                            <br>
                            <h5 class="text-uppercase">Recent Orders</h5>
                            
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="user-orders-list">
                                        <div class="responsive-table">
                                            <table class="table table-hover" id="myOrdersTable">
                                                <thead>
                                                  <tr>
                                                    <th scope="col">Order #</th>
                                                    <th scope="col">Total</th>
                                                    <th scope="col">Status</th>
                                                    <th scope="col">Date</th>

                                                    <th scope="col">Details</th>
                                                    <th scope="col">Delete</th>
                                                    <th scope="col">Edit time</th>
                                                    <th scope="col">Order More..</th>

                                                  </tr>
                                                </thead>
                                                <tbody>
                                                    {% for order in recent_orders%}
                                                  <tr>
                                                    <td> {{order.order_number}} </td>
                                                    <td> ₹{{order.total}}</td>
                                                    <td> {{order.status}}</td>
                                                    <td> {{order.created_at}}</td>
                                                    <td><a href="{% url 'order_detail' order.order_number %}" class="btn btn-primary"> Details</a> </td>
                                                    <td><a href="{% url 'order_cancel' order.order_number %}" class="btn btn-danger"> Cancel</a> </td>
                                                    <td><a href="{% url 'pre_order_time_change' order.order_number %}" class="btn btn-secondary"> Edit </a> </td>
                                                    <td>
                                                        <a href="{% url 'restaurant_detail' restaurant_slug %}" class="btn btn-warning"> Continue Ordering </a>

                                                    </td>

                                                  </tr>
                                                  {% endfor %}
                                                  
                                                </tbody>
                                              </table>

                                        </div>												
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/forgot_password.html
{%extends 'base.html' %}

{% block content %}
<style>
    body {
        background: #f5f5f5;
    }

    .rounded-lg {
        border-radius: 1rem;
    }

    .nav-pills .nav-link {
        color: #555;
    }

    .nav-pills .nav-link.active {
        color: #fff;
    }
</style>

<script>
    $(document).ready(function () {
        $(".nav-pills a").click(function () {
            $(this).tab("show");
        });
    });
</script>
</head>

<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-7 mx-auto">
                <div class="bg-white rounded-lg shadow-sm p-5">
                    <h2 style="text-align: center;">Forgot Password?</h2>
                    <h4 style="text-align: center;"> Enter your email below to reset password.</h4>
                    <div class="tab-content">
                        <div id="nav-tab-paypal" class="tab-pane fade show active">
                            <form action="{% url 'forgot_password' %}" role="form" method="post" enctype="multipart/form-data">
                                {%csrf_token%}
                                <div class="form-group">
                                    <div class="field-holder">
                                        <label for="identifier">Username</label>
                                        <input type="text" name="identifier" placeholder="Enter your Username (Email or Phone Number)" class="form-control" required>
                                    </div>
                                </div>
                                <button type="submit"
                                    class="subscribe btn btn-primary btn-block rounded-pill shadow-sm" value="Forgot Password">
                                    Submit
                                </button>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        {% include 'includes/alerts.html' %}
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
                var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                    return new bootstrap.Tooltip(tooltipTriggerEl);
                });
            });
            </script>
    {% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block content %}
<style>
    body {
        background: #f5f5f5;
    }

    .rounded-lg {
        border-radius: 1rem;
    }

    .nav-item {
        list-style-type: none; /* Remove the default list marker */
 
    }
    .nav-pills .nav-link {
        color: #555;
    }

    .nav-pills .nav-link.active {
        color: #fff;
    }
    .welcome-message {
        padding: 20px;
        margin-bottom: 1.5rem; /* Adds space below the message */
        background-color: #f0f8ff; /* Light Alice Blue background */
        border-radius: 10px; /* Rounded corners */
        border: 2px solid #add8e6; /* Light Blue border */
    }
    
    .welcome-message h4 {
        font-size: 1.75rem; /* Slightly larger font size */
        color: #4682b4; /* Steel Blue color for text */
        margin: 0; /* Remove default margin */
        font-weight: 700; /* Bold text */
        font-family: 'Arial', sans-serif; /* Font change */
    }
</style>

<script>
    $(document).ready(function () {
        $(".nav-pills a").click(function () {
            $(this).tab("show");
        });
    });
</script>

<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-7 mx-auto">
                <div class="bg-white rounded-lg shadow-sm p-5">
                    <div class="welcome-message text-center mb-4">
                        <h4>Good to see you again!</h4>
                    </div>

                    <ul role="tablist" class="nav bg-light nav-pills rounded-pill nav-fill mb-3">
                        <li class="nav-item">
                            <a href="{% url 'registerUser' %}" class="nav-link rounded-pill">
                                <i class="fa-solid fa-user"></i>
                                Sign-Up
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'login' %}" class="nav-link active rounded-pill">
                                <i class="fa-regular fa-user"></i>
                                Login
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="nav-tab-login" class="tab-pane fade show active">
                            <form action="{% url 'login' %}" role="form" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <div class="field-holder">
                                        <label>Username</label>
                                        <input type="text" name="identifier" placeholder="Please enter your email..." class="form-control">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="field-holder">
                                        <label>Password</label>
                                        <input type="password" name="password" placeholder="Enter Your Password" class="form-control">
                                    </div>
                                </div>
                                <button type="submit" class="subscribe btn btn-primary w-100 rounded-pill shadow-sm mt-3">
                                    Submit
                                </button>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <a href="{% url 'forgot_password' %}" class="float">Forgot Password?</a>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        {% include 'includes/alerts.html' %}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl);
            });
        });
        </script>
        
{% endblock content %}

templates/accounts/r_contactUs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'includes/alerts.html' %}

<div class="main-section">
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <!-- Sidebar -->
                <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
                    {% include 'includes/r_sidebar.html' %}
                </div>
                
                <!-- Main Content -->
                <div class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
                    <div class="bg-light rounded-lg shadow-sm p-4">
                        <div class="text-center mb-4">
                            <h4 class="display-4 font-weight-bold text-primary">Contact Us</h4>
                            <p class="lead text-muted">We'd love to hear from you. Please fill out the form below to get in touch with us.</p>
                        </div>
                        {% if form_submitted %}
                            <div class="alert alert-success">
                                <h4 class="alert-heading">Thank you for reaching out!</h4>
                                <p>Your message has been sent successfully.</p>
                            </div>
                        {% else %}
                            <form action="{% url 'r_contact_us' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_name" class="font-weight-bold">Name</label>
                                    <input type="text" name="name" id="id_name" class="form-control" placeholder="Enter your name" required>
                                </div>
                                <div class="form-group">
                                    <label for="id_message" class="font-weight-bold">Message</label>
                                    <textarea name="message" id="id_message" class="form-control" rows="4" placeholder="Enter your message" required></textarea>
                                </div>
                                <input type="hidden" name="user_type" value="{{ user_type }}">
                                <button type="submit" class="subscribe btn btn-primary w-100 rounded-pill shadow-sm mt-3 ">
                                    Send Message
                                </button>
                                {% if form.errors %}
                                    <div class="alert alert-danger mt-3">
                                        <ul class="mb-0">
                                            {% for field in form %}
                                                {% if field.errors %}
                                                    {% for error in field.errors %}
                                                        <li>{{ error }}</li>
                                                    {% endfor %}
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('form').submit(function (event) {
            var name = $('#id_name').val().trim();
            var message = $('#id_message').val().trim();

            if (!name) {
                event.preventDefault();
                alert('Please provide your name.');
            } else if (!message) {
                event.preventDefault();
                alert('Please provide a message.');
            }
        });
    });
</script>
{% endblock content %}

templates/accounts/test.html
{%extends 'base.html' %}