orders/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap




urlpatterns = [
    path('place-order/', views.place_order, name = 'place_order'),
    path('create_order_api/', views.create_order_api, name='create_order_api'),
    path('payment-webhook/', views.payment_webhook, name='payment_webhook'),
    path('order_complete/', views.order_complete, name='order_complete'),
    # path('restaurant_cash_order/', views.restaurant_cash_order, name='restaurant_cash_order'),

    
]

orderzy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomeSitemap
from marketplace.sitemaps import MarketplaceSitemap, RestaurantSitemap
from customers.sitemaps import CustomerSitemap
from accounts.sitemaps import AccountsSitemap
from orders.sitemaps import OrdersSitemap
from django.views.generic import TemplateView

sitemaps = {
    'home': HomeSitemap,
    'marketplace': MarketplaceSitemap,
    'restaurant': RestaurantSitemap,
    'customers': CustomerSitemap,
    'accounts': AccountsSitemap,
    'orders': OrdersSitemap,
}
urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("admin/", admin.site.urls),
    path('', views.home, name = 'home'),
    path('base/', views.base, name = 'base'),
    
    path('', include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),
    #CART
    path('cart/', MarketplaceViews.cart, name='cart'),
    
    #SEARCH PATH
    path('search/', MarketplaceViews.search, name='search'),
    
    path('checkout/', MarketplaceViews.checkout, name='checkout'),
    
    
    path('orders/', include('orders.urls')),
    
    path('about/', views.about_us, name='about_us'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact_us, name='contact_us'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('refund_policy/', views.refund_policy, name='refund_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),

    
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.fields.related import  OneToOneField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point



class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email=None,phone_number=None, password=None,**extra_fields):
        if not username:
            raise ValueError('Username is required')
        if not password:
            raise ValueError('Password is required')
        
        if '@' in username:
            email = self.normalize_email(username)
            phone_number = None
        else:
            email = None
            phone_number = username
        
        user = self.model(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            phone_number=phone_number,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    
    
    def create_superuser(self, first_name, last_name, username, email=None,phone_number=None, password=None, **extra_fields):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            password=password,
            **extra_fields
        )
        user.is_admin=True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    
    RESTAURANT = 1
    CUSTOMER = 2
 
    
    ROLE_CHOICE = (
        (RESTAURANT, 'Restaurant'),
        (CUSTOMER, 'Customer')

        
    )
    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True, blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)
    
    #required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False) 

 
    USERNAME_FIELD = 'username' 
    REQUIRED_FIELDS = ['first_name', 'last_name']
    
    objects = UserManager()

    def __str__(self):
        return self.username
    
    def save(self, *args, **kwargs):
        if '@' in self.username:
            self.email = self.username
            self.phone_number = None
        else:
            self.email = None
            self.phone_number = self.username

        super(User, self).save(*args, **kwargs)
    
    def has_perm(self,perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Restaurant'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}".strip()
    


class UserProfile(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE, blank=True, null = True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null = True)
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null = True)
    address = models.CharField(max_length=250, blank=True, null = True)
    country = models.CharField(max_length=15, blank=True, null = True)
    state = models.CharField(max_length=15, blank=True, null = True)
    city = models.CharField(max_length=15, blank=True, null = True)
    pin_code = models.CharField(max_length=6, blank=True, null = True)
    latitude = models.CharField(max_length=20, blank=True, null = True)
    longitude = models.CharField(max_length=20, blank=True, null = True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    

    
    def __str__(self):
        if self.user:
            return self.user.username or 'No username'
        return 'No user'
    
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
            return super(UserProfile, self).save(*args, **kwargs)
        return super(UserProfile, self).save(*args, **kwargs)
    
    # models.py


class ContactMessage(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=100)
    message = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} at {self.sent_at}"



class Newsletter(models.Model):
    email = models.EmailField(unique=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from .models import *
from .validators import allow_only_images_validator

        
class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter your password'
        })
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username','password']
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Please enter your email...'
        })
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')

        if not username:
            raise forms.ValidationError("Username is required.")
        
        if '@' in username:
            email = username
            if User.objects.filter(username=email).exists():
                raise forms.ValidationError("User with this Email already exists.")
        else:
            phone_number = username
            if User.objects.filter(username=phone_number).exists():
                raise forms.ValidationError("User with this Phone Number already exists.")

        return cleaned_data
    
class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder' : 'Start Typing...', 'required':'required'}))
    profile_picture = forms.FileField(widget = forms.FileInput(attrs={'class':'btn btn-info'}), validators=[allow_only_images_validator])
    cover_photo = forms.FileField(widget = forms.FileInput(attrs={'class':'btn btn-info'}), validators=[allow_only_images_validator])
    
    
    class Meta:
        model = UserProfile
        fields = ['profile_picture','cover_photo','address','country','state','city','pin_code','latitude','longitude']
        
        
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field =='latitude' or field == 'longitude':
                self.fields[field].widget.attrs['readonly'] = 'readonly'
                
                

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','phone_number']
        
        



class LoginForm(forms.Form):
    identifier = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Email or Mobile Number'}))
    password = forms.CharField(widget=forms.PasswordInput())



class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'message']

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<script async src="https://www.googletagmanager.com/gtag/js?id=G-J7PJXLKWWM"></script>
	<script>
  		window.dataLayer = window.dataLayer || [];
  		function gtag(){dataLayer.push(arguments);}
  		gtag('js', new Date());

  		gtag('config', 'G-J7PJXLKWWM');
	</script>
	<meta charset="utf-8">
	<meta name="google-site-verification" content="nJpTY9SMK92TG6-ZZ1fjU8BuuGQ7GoVfYymrfGu16XE" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>  Orderzy | {% block title %} {% endblock %} </title>
	<meta name="description" content="Pre-order from nearby restaurants with Orderzy for a smooth dining experience. Discover new spots and enjoy your meal without waiting.">
	<meta name="keywords" content="Orderzy, online food ordering, local restaurants, nearby dining, order ahead, restaurant deals, discover new spots, quick service, food ordering app, neighborhood restaurants">
	<meta name="author" content="Orderzy">
	<meta property="og:url" content="https://orderzy.in">
	<meta property="og:type" content="website">
	<meta property="og:title" content="Order Ahead, Relax Later with Orderzy | Pre Order at Nearby Restaurants">
	<meta property="og:description" content="Preorder from nearby restaurants with Orderzy. Save time and enhance your dining experience by discovering new spots near you.">
	<!-- <meta property="og:image" content="{% static 'images/Orderzy_og_600.png' %}">
	<meta name="twitter:image" content="{% static 'images/orderzy_twitter.png' %}"> -->
	<meta property="og:image" content="https://orderzy.in/static/images/Orderzy_og_600.png">
	<meta name="twitter:image" content="https://orderzy.in/static/images/orderzy_twitter.png">


	<link rel="icon" href="{% static 'favicon/favicon.ico' %}" type="image/x-icon">
	<link rel="icon" href="{% static 'favicon/favicon-16x16.png' %}" sizes="16x16" type="image/png">
	<link rel="icon" href="{% static 'favicon/favicon-32x32.png' %}" sizes="32x32" type="image/png">
	<link rel="icon" href="{% static 'favicon/favicon-48x48.png' %}" sizes="48x48" type="image/png">
	<link rel="icon" href="{% static 'favicon/android-chrome-512x512.png' %}" sizes="512x512" type="image/png">
	
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">

	<link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-TileImage" content="{% static 'favicon/mstile-150x150.png' %}">
	<meta name="theme-color" content="#ffffff">
	<link rel="canonical" href="https://orderzy.in">

	<link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Gowun+Batang:wght@400;700&family=Montserrat:wght@400;700&family=Noto+Serif+Old+Uyghur&family=Open+Sans:wght@400;700;800&family=Sansita:wght@400;700&display=swap" rel="stylesheet">


	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
	<link href="{% static 'css/custom.css' %}" rel="stylesheet">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css">
	{% block extra_css %}
    {% endblock extra_css %}
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.3.0/lazysizes.min.js" async></script>

	<script src="https://cdn.datatables.net/2.0.8/js/dataTables.min.js"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=USD"></script>
	<script src="https://sdk.cashfree.com/js/v3/cashfree.js"></script>
	<script>
    let cashfree;  // Declare cashfree globally
    document.addEventListener('DOMContentLoaded', function () {
        cashfree = Cashfree({
            mode: "production"  // Change to "production" when going live
        });
    });
	</script>

	

	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	

	{% if '/profile/' in request.path or '/' == request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}&libraries=places&loading=async&callback=initAutoComplete" async defer></script>
	{% endif %}
	<script type="text/javascript" language="javascript" class="init">
		document.addEventListener('DOMContentLoaded', function () {
			let table = new DataTable('#myOrdersTable');
		});
	</script>
	<script type="application/ld+json">
		{
		  "@context": "https://schema.org",
		  "@type": "Organization",
		  "name": "Orderzy",
		  "url": "https://orderzy.in",
		  "logo": "https://orderzy.in/static/images/Orderzy_og_600.png",
		  "contactPoint": {
			"@type": "ContactPoint",
			"telephone": "9238008672",
			"contactType": "Customer Service",
			"areaServed": "IN",
			"availableLanguage": "English"
		  },
		  "sameAs": [
			"https://www.facebook.com/orderzy",
			"https://www.instagram.com/orderzy"
		  ]
		}
		</script>
	{% block extra_js %}
    {% endblock extra_js %}
		

	<style>
		body,
		.main-section p,
		.mce-content-body p {
			font: Normal 14px/24px "Open Sans", sans-serif;
			letter-spacing: 0px;
			text-transform: none;
			color: #515151 !important;
		}

		.dt-input{
			width: auto !important;
		}
		.dt-input + label {
			margin-left: 10px; /* Adjust the value as needed */
		  }
	</style>

</head>

<body>

	{% include 'includes/navbar.html' %}


	{% block content %}

	{%endblock content %}

	{% include 'includes/footer.html' %}
	

templates/google35dfab3d1346c940.html
google-site-verification: google35dfab3d1346c940.html

templates/home.html
{% extends 'base.html' %} {% load static %}
{% block title %} Skip the Line, Enjoy Your Time! {% endblock %}
 {% block content %}
<div class="main-section">
   <div class="page-section  main-search-bar" style=" width: 100vw; height: 70vh; background: url({% static 'extra-images/bg11.jpg' %}) no-repeat center / cover;">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
		<div class="element-title">
				<div class="brand_name">
					<h1>Orderzy</h1>
				</div>

        <p style=" margin-top:2.5%; font-size: 18px; letter-spacing: 1px; color: #155edd; text-align:center; ">
          Skip the Line, Enjoy Your Time!</p>
		</div>
		<div class="main-search fancy ">
						<form action="{% url 'search' %}" method="GET">
              <div class="row justify-content-center">
                <div class="col-lg-10 col-md-10">
                  <div class="form-container d-flex justify-content-center align-items-center" style="background-color: rgb(201, 201, 205); padding: 20px; border-radius: 15px;">
                   
							<div class="row w-100">
								<div class="col-lg-5 col-md-5 col-sm-3 col-xs-12">
									<div class="field-holder holder_radius">
										<input type="text" name="keyword" placeholder="Resturant name or Food name" class="form-control">
									</div>
								</div>
           
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
              <div class="field-holder holder_radius position-relative" style="position: relative;">
                  <span class="foodbakery-search-location-icon position-absolute" 
                        style="position: absolute; top: 50%; left: 10px; transform: translateY(-50%); font-size: 1.2rem; color: #999;">
                      <i class="icon-location"></i>
                  </span>
                  <input type="text" name="address" class="form-control ps-5" id="id_address" placeholder="All Locations" 
                         style="padding-left: 2.5rem; vertical-align: middle;">
                  <input type="hidden" name="lat" value="" id="id_latitude">
                  <input type="hidden" name="lng" value="" id="id_longitude">
              </div>
          </div>
                
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
									<div class="field-holder holder_radius">
										<input type="submit" value="Search">
									</div>
								</div>
							</div>
              </div>
              </div>
              </div>
						</form>
					</div>
	</div>
   </div>

  <div
    class="page-section nopadding cs-nomargin"
    style="
      margin-top: 0px;
      padding-top: 60px;
      padding-bottom: 0px;
      margin-bottom: 0px;
      background: #ffffff;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title align-left">
            <h2>Top Restaurants</h2>
            <p>Explore restaurants, bars, and cafés by locality</p>
          </div>
        </div>
        <div
          class="col-lg-12 col-md-12 col-sm-12 col-xs-12"
          style="padding-right: 0 !important; padding-left: 0 !important"
        >
          <div class="company-logo">
            <ul>
              {% for restaurant in restaurants %}
              <li class="has-border">
                <figure>
                  {% if restaurant.user_profile.profile_picture %}
                  <a
                    href="{% url 'restaurant_detail' restaurant.restaurant_slug %}"
                    ><img
                      data-src="{{ restaurant.user_profile.profile_picture.url }}"
                      height="125"
                      class="attachment-full size-full wp-post-image home-restaurant-img lazyload"
                      alt="Profile Picture" loading="lazy"
                  /></a>
                  {% else %}
                  <a
                    href="{% url 'restaurant_detail' restaurant.restaurant_slug %}"
                    ><img
                      data-src="{% static 'images/default-profile.png' %}"
                      height="125"
                      class="lazyload attachment-full size-full wp-post-image home-restaurant-img"
                      alt="Profile Picture" loading="lazy"
                  /></a> 
                  {% endif %}
                </figure>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div
    class="page-section nopadding cs-nomargin"
    style="
      margin-top: 0px;
      padding-top: 60px;
      padding-bottom: 50px;
      margin-bottom: 0px;
      background: #ffffff;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title align-center">
            <h2>Choose From Most Popular Restaurants</h2>
          </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="listing fancy">
            <ul class="row">

              {% for restaurant in restaurants %}
              <li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="list-post featured">
                  <div class="img-holder">
                    <figure>
                      <a
                        href="{% url 'restaurant_detail' restaurant.restaurant_slug %}"
                      >
                        {% if restaurant.user_profile.profile_picture %}
                        <img
                          data-src="{{ restaurant.user_profile.profile_picture.url }}"
                          class="lazyload img-thumb wp-post-image"
                          alt="Profile Picture" loading="lazy"
                        />
                        {% else %}
                        <img
                          data-src="{% static 'images/default-profile.png' %}"
                          class="lazyload img-thumb wp-post-image"
                          alt="Profile Picture" loading="lazy"
                        />
                        {% endif %}
                      </a>
                    </figure>
                    {% if restaurant.is_open %}
                    <span class="restaurant-status open">
                      <em class="bookmarkRibbon"></em>Open
                    </span>
                    {% else %}
                    <span class="restaurant-status close">
                      <em class="bookmarkRibbon"></em>Close
                    </span>
                    {% endif %}
                  </div>
                  <div class="text-holder">
                    <div class="post-title">
                      <h5>
                        <a
                          href="{% url 'restaurant_detail' restaurant.restaurant_slug %}"
                          >{{ restaurant }}</a
                        >
                      </h5>
                    </div>
                    {% if restaurant.user_profile.city and restaurant.user_profile.state and restaurant.user_profile.pin_code %}
                    <span>{{ restaurant.user_profile.city }}, {{ restaurant.user_profile.state }}, {{ restaurant.user_profile.pin_code }}</span>
                    {% endif %} 
					
			

                    {% if restaurant.kms|default_if_none:"" %}
                        <br>
                        <span><small><b>{{ restaurant.kms }} km </b>away</small></span>
                    {% endif %}

                  </div>
                  <div class="list-option">
                    <a
                      href="javascript:void(0);"
                      class="shortlist-btn"
                      data-bs-toggle="modal"
                      data-bs-target="#sign-in"
                    >
                      
                    </a>
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}